development:
  bucket: squarestays-img-dev
  access_key_id: AKIAICSWWKMXN4NP7FIQ
  secret_access_key: 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

production:
  bucket: squarestays-img-staging
  access_key_id: AKIAICSWWKMXN4NP7FIQ
  secret_access_key: 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
