#
# Format:
#
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#

########################################################################################################################################
squarestays:
########################################################################################################################################
  app:   squarestays
  config:
    BUNDLE_WITHOUT:       "development:test"
    SITE_URL:             http://www.squarestays.com
    PRODUCT_CLASS_NAME:   Place
    # Database and CDN
    DATABASE_URL:         mysql2://heypaladmin:HYpl99db@heypal-useast-1.c7xsjolvk9oh.us-east-1.rds.amazonaws.com/SquareStays_production
    S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
    S3_SECRET_ACCESS_KEY: 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
    S3_BUCKET:            squarestays-img-production
    # Social Networks
    FB_APP_ID:            201854953233705
    FB_APP_SECRET:        5a773c1f43daaaefb0a169fc388ba1e0
    TW_APP_ID:            KkHFOnyPPPFjUYcjVpyLA
    TW_APP_SECRET:        rbNU7xVyPGD6zr3QD36pFaZO6bIo32qRygcfOwgjPA
    # Security
    SECRET_TOKEN:         b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY:     _SquareStaysProductionFrontEnd_session
    # External Services
    RECAPTCHA_PUB_KEY:    6Lcoo9ASAAAAALmNU_4LUOy4W11qRueZ9C3FXu3h
    RECAPTCHA_PVT_KEY:    6Lcoo9ASAAAAAHM-sKYibqSA16qaCYR9IaG8SknD
    RAKISMET_KEY:         bcba68e5b091
    RAKISMET_URL:         http://www.squarestays.com/
    # Paypal
    PAYPAL_ACCOUNT:       sales@heypal.com
    PAYPAL_MODE:          production

########################################################################################################################################
squarestage:
########################################################################################################################################
  app:   squarestage
  config:
    BUNDLE_WITHOUT:       "development:test"
    SITE_URL:             http://squarestage.herokuapp.com
    PRODUCT_CLASS_NAME:   Place
    # Database and CDN
    DATABASE_URL:         mysql2://heypaladmin:HYpl99db@heypal-useast-1.c7xsjolvk9oh.us-east-1.rds.amazonaws.com/heypaldb
    S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
    S3_SECRET_ACCESS_KEY: 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
    S3_BUCKET:            squarestays-img-staging
    # Social Networks
    FB_APP_ID:            294052747281058
    FB_APP_SECRET:        c8fbc31a070e9aa9bcbba3d702d5ec1a
    TW_APP_ID:            7IhUH1SkVKa7VNVDY5Bdw
    TW_APP_SECRET:        iv3EywCFcm9xzAdSxlsCEnViSdXjDhBz0x9Xxb5Jc
    # Security
    SECRET_TOKEN:         b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY:     _SquareStaysStagingFrontEnd_session
    # External Services
    RECAPTCHA_PUB_KEY:    6Lcuo9ASAAAAAGx1sEf6qvddoPnTnvZ9QjSXAuNR
    RECAPTCHA_PVT_KEY:    6Lcuo9ASAAAAAOYdrtLjPruEU0ZmferG5C_aTCEK
    RAKISMET_KEY:         bcba68e5b091
    RAKISMET_URL:         http://squarestage.herokuapp.com/
    # Paypal
    PAYPAL_ACCOUNT:       nico_1334303615_biz@heypal.com
    PAYPAL_MODE:          test

########################################################################################################################################
tse-demo:
########################################################################################################################################
  app:   tse-demo
  config:
    BUNDLE_WITHOUT:       "development:test"
    SITE_URL:             http://demo.thesharingengine.com
    PRODUCT_CLASS_NAME:   Place
    # Database and CDN
    DATABASE_URL:         mysql2://heypaladmin:HYpl99db@heypal-useast-1.c7xsjolvk9oh.us-east-1.rds.amazonaws.com/tsedemo
    S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
    S3_SECRET_ACCESS_KEY: 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
    S3_BUCKET:            tsedemo
    # Social Networks
    FB_APP_ID:            150030298466716
    FB_APP_SECRET:        c3ee9ccfd1d9abf2a60b2804078d3421
    TW_APP_ID:            8pFl2HlRVMjj5iKin962w
    TW_APP_SECRET:        8BPpQn2VSqtkMWNYw7CpkY2ZYeyCENaTktRORJjW8
    # Security
    SECRET_TOKEN:         b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY:     _SquareStaysStagingFrontEnd_session
    # External Services
    RECAPTCHA_PUB_KEY:    6Lcuo9ASAAAAAGx1sEf6qvddoPnTnvZ9QjSXAuNR
    RECAPTCHA_PVT_KEY:    6Lcuo9ASAAAAAOYdrtLjPruEU0ZmferG5C_aTCEK
    RAKISMET_KEY:         bcba68e5b091
    RAKISMET_URL:         http://demo.thesharingengine.com/
    # Paypal
    PAYPAL_ACCOUNT:       nico_1334303615_biz@heypal.com
    PAYPAL_MODE:          test
