#
# Format:
# 
# <heroku_san shorthand name>:
#   app: <Heroku app name>
#   stack: <Heroku stack, optional>
#   config:
#     - <Heroku config:var name>: <Heroku config:var value>
#
production: 
  app:   squarestays
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT:       "development:test"
    S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
    S3_SECRET_ACCESS_KEY: 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
    S3_BUCKET:            squarestays-img-production
    FB_APP_ID:            201854953233705
    FB_APP_SECRET:        5a773c1f43daaaefb0a169fc388ba1e0
    FRONTEND_PATH:        http://www.squarestays.com
    TW_APP_ID:            KkHFOnyPPPFjUYcjVpyLA
    TW_APP_SECRET:        rbNU7xVyPGD6zr3QD36pFaZO6bIo32qRygcfOwgjPA
    BACKEND_PATH:         https://squarestays-backend.heroku.com
    SECRET_TOKEN:         b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY:     _SquareStaysProductionFrontEnd_session

staging:
  app:   frontend-heypal
  stack: bamboo-mri-1.9.2
  config:
    BUNDLE_WITHOUT:       "development:test"
    S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
    S3_SECRET_ACCESS_KEY: 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
    S3_BUCKET:            squarestays-img-staging
    FB_APP_ID:            294052747281058
    FB_APP_SECRET:        c8fbc31a070e9aa9bcbba3d702d5ec1a
    FRONTEND_PATH:        http://frontend-heypal.heroku.com
    TW_APP_ID:            7IhUH1SkVKa7VNVDY5Bdw
    TW_APP_SECRET:        iv3EywCFcm9xzAdSxlsCEnViSdXjDhBz0x9Xxb5Jc
    BACKEND_PATH:         https://backend-heypal.heroku.com
    SECRET_TOKEN:         b6e5e9e331352b88ed6b14704160ee6e7aeee1989d00bc416d34428c213518d9d4d3d6b1dee34587d7a1c02bbd69754212b2815f9e8c2ac3915c54ac18ac7771
    COOKIE_STORE_KEY:     _SquareStaysStagingFrontEnd_session
