defaults: &defaults
  S3_ACCESS_KEY_ID:     AKIAJOJEIAZ6LOVHDFDA
  S3_SECRET_ACCESS_KEY: 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
  FB_APP_ID:            289917857692700
  FB_APP_SECRET:        e21346334029581a59ea6d0ddcfb7dfe
  BACKEND_PATH:         'http://localhost:3000'
  FRONTEND_PATH:        'http://localhost:3005'
  SECRET_TOKEN:         4fafcf33a55a5b7d6cd2be869e9f450b65ea004e421c05b459ebb2643e7a6b3201d5f1e2da0ce7310102c7d48368b0d100087f73545fd14aff0de8050f818a61
  MAILER_SENDER:        SquareStays.com <noreply@squarestays.com>
  PEPPER_TOKEN:         Z8TxukxAnyxxjRgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUuYgTcaWywccE3CA8Gdgs6jSB3Y3v4AzHjFvPFxpaENsJCnrkDUWywccE3CA8Gdgs6jSB3YAnyxxjRgs6jS
  PAYPAL_ACCOUNT:       nico_1334303615_biz@heypal.com
  PAYPAL_MODE:          test
  RECAPTCHA_PUB_KEY:    6Lcuo9ASAAAAAGx1sEf6qvddoPnTnvZ9QjSXAuNR
  RECAPTCHA_PVT_KEY:    6Lcuo9ASAAAAAOYdrtLjPruEU0ZmferG5C_aTCEK
  RAKISMET_KEY:         bcba68e5b091
  RAKISMET_URL:         http://localhost:3005
  PRODUCT_CLASS_NAME:   Place

development:
  <<: *defaults
  S3_BUCKET:        squarestays-img-dev
  COOKIE_STORE_KEY: _SquareStaysDevelopmentBackEnd_session

test:
  <<: *defaults
  STORAGE:          filesystem
  S3_BUCKET:        squarestays-img-test
  COOKIE_STORE_KEY: _SquareStaysTestBackEnd_session